var json_346_centri_colpiti_molise_lazio_merid_1 = {
"type": "FeatureCollection",
"name": "346_centri_colpiti_molise_lazio_merid_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Toponimo": "Alife (CE)", "Descrizion": "<br>Latitudine: <b>41.328</b> <br>Longitudine: <b>14.330</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.33, 41.328 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Isernia (IS)", "Descrizion": "<br>Latitudine: <b>41.594</b> <br>Longitudine: <b>14.231</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.231, 41.594 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Sepino (CB)", "Descrizion": "<br>Latitudine: <b>41.408</b> <br>Longitudine: <b>14.619</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.619, 41.408 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Telese (BN)", "Descrizion": "<br>Latitudine: <b>41.217</b> <br>Longitudine: <b>14.527</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.527, 41.217 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Venafro (IS)", "Descrizion": "<br>Latitudine: <b>41.486</b> <br>Longitudine: <b>14.044</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII-IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.044, 41.486 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Abellinum (AV)", "Descrizion": "<br>Latitudine: <b>40.922</b> <br>Longitudine: <b>14.827</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.827, 40.922 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Roma (RM)", "Descrizion": "<br>Latitudine: <b>41.896</b> <br>Longitudine: <b>12.482</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IV-V</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 12.482, 41.896 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Bovianum Vetus (IS)", "Descrizion": "<br>Latitudine: <b>41.743</b> <br>Longitudine: <b>14.379</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>Non classificata</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.387445944091807, 41.739733926229846 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Cales (CE)", "Descrizion": "<br>Latitudine: <b>41.182</b> <br>Longitudine: <b>14.130</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>Non classificata</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.132718697550368, 41.199752484509617 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Teanum (CE)", "Descrizion": "<br>Latitudine: <b>41.250</b> <br>Longitudine: <b>14.057</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>Non classificata</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.067617668134256, 41.251112708552661 ] } }
]
}
