var json_1349_centri_colpiti_molise_lazio_merid_4 = {
"type": "FeatureCollection",
"name": "1349_centri_colpiti_molise_lazio_merid_4",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Toponimo": "Atina (FR)", "Descrizion": "<br>Latitudine: <b>41.620</b> <br>Longitudine: <b>13.800</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>X</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.8, 41.62 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Venafro (IS)", "Descrizion": "<br>Latitudine: <b>41.486</b> <br>Longitudine: <b>14.044</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>X</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.044, 41.486 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Isernia (IS)", "Descrizion": "<br>Latitudine: <b>41.594</b> <br>Longitudine: <b>14.231</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX-X</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.231, 41.594 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Abbazia di San Vincenzo al Volturno (IS)", "Descrizion": "<br>Latitudine: <b>41.651</b> <br>Longitudine: <b>14.088</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.088, 41.651 ] } },
{ "type": "Feature", "properties": { "Toponimo": "San Domenico (FR)", "Descrizion": "<br>Latitudine: <b>41.698</b> <br>Longitudine: <b>13.579</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.579, 41.698 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Alvito (FR)", "Descrizion": "<br>Latitudine: <b>41.689</b> <br>Longitudine: <b>13.742</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.742, 41.689 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Cardito (FR)", "Descrizion": "<br>Latitudine: <b>41.591</b> <br>Longitudine: <b>13.974</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.974, 41.591 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Cerasuolo (IS)", "Descrizion": "<br>Latitudine: <b>41.585</b> <br>Longitudine: <b>14.021</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.021, 41.585 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Montecassino (FR)", "Descrizion": "<br>Latitudine: <b>41.490</b> <br>Longitudine: <b>13.814</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.814, 41.49 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Sant'Elia Fiumerapido (FR)", "Descrizion": "<br>Latitudine: <b>41.541</b> <br>Longitudine: <b>13.866</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.866, 41.541 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Sant'Agnello (FR)", "Descrizion": "<br>Latitudine: <b>41.801</b> <br>Longitudine: <b>13.316</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII-IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.316, 41.801 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Sora (FR)", "Descrizion": "<br>Latitudine: <b>41.719</b> <br>Longitudine: <b>13.613</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII-IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.613, 41.719 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Veroli (FR)", "Descrizion": "<br>Latitudine: <b>41.692</b> <br>Longitudine: <b>13.419</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII-IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.419, 41.692 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Aversa (CE)", "Descrizion": "<br>Latitudine: <b>40.974</b> <br>Longitudine: <b>14.207</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.207, 40.974 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Le Fratte (FR)", "Descrizion": "<br>Latitudine: <b>41.355</b> <br>Longitudine: <b>13.749</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.749, 41.355 ] } },
{ "type": "Feature", "properties": { "Toponimo": "San Vittore del Lazio (FR)", "Descrizion": "<br>Latitudine: <b>41.461</b> <br>Longitudine: <b>13.931</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.931, 41.461 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Ariano (AV)", "Descrizion": "<br>Latitudine: <b>41.154</b> <br>Longitudine: <b>15.090</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VII-VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 15.09, 41.154 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Napoli (NA)", "Descrizion": "<br>Latitudine: <b>40.856</b> <br>Longitudine: <b>14.260</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 14.26, 40.856 ] } }
]
}
