var json_1349_centri_colpiti_abruzzo_aquilano_3 = {
"type": "FeatureCollection",
"name": "1349_centri_colpiti_abruzzo_aquilano_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Toponimo": "Bazzano (AQ)", "Descrizion": "<br>Latitudine: <b>42.338</b> <br>Longitudine: <b>13.454</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.454, 42.338 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Santa Maria della Vittoria (AQ)", "Descrizion": "<br>Latitudine: <b>42.074</b> <br>Longitudine: <b>13.358</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.358, 42.074 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Colle Sambuco (RI)", "Descrizion": "<br>Latitudine: <b>42.266</b> <br>Longitudine: <b>13.174</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.174, 42.266 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Gamagna (RI)", "Descrizion": "<br>Latitudine: <b>42.260</b> <br>Longitudine: <b>13.133</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.133, 42.26 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Girgenti (RI)", "Descrizion": "<br>Latitudine: <b>42.236</b> <br>Longitudine: <b>13.075</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.075, 42.236 ] } },
{ "type": "Feature", "properties": { "Toponimo": "L'Aquila (AQ)", "Descrizion": "<br>Latitudine: <b>42.356</b> <br>Longitudine: <b>13.396</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.396, 42.356 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Mareri (RI)", "Descrizion": "<br>Latitudine: <b>42.267</b> <br>Longitudine: <b>13.090</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.09, 42.267 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Petrella Salto (RI)", "Descrizion": "<br>Latitudine: <b>42.295</b> <br>Longitudine: <b>13.068</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.068, 42.295 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Poggio Poponesco (RI)", "Descrizion": "<br>Latitudine: <b>42.270</b> <br>Longitudine: <b>13.118</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.118, 42.27 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Radicaro (RI)", "Descrizion": "<br>Latitudine: <b>42.250</b> <br>Longitudine: <b>13.151</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.151, 42.25 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Santa Maria (RI)", "Descrizion": "<br>Latitudine: <b>42.266</b> <br>Longitudine: <b>13.171</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.171, 42.266 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Staffoli (RI)", "Descrizion": "<br>Latitudine: <b>42.312</b> <br>Longitudine: <b>13.056</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.056, 42.312 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Vallebona (RI)", "Descrizion": "<br>Latitudine: <b>42.273</b> <br>Longitudine: <b>13.086</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.086, 42.273 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Subiaco (RM)", "Descrizion": "<br>Latitudine: <b>41.926</b> <br>Longitudine: <b>13.095</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VIII-IX</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.095, 41.926 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Roma (RM)", "Descrizion": "<br>Latitudine: <b>41.896</b> <br>Longitudine: <b>12.482</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VII-VIII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 12.482, 41.896 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Tarano (RI)", "Descrizion": "<br>Latitudine: <b>42.356</b> <br>Longitudine: <b>12.595</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 12.595, 42.356 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Ascoli Piceno (AP)", "Descrizion": "<br>Latitudine: <b>42.854</b> <br>Longitudine: <b>13.578</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>VI-VII</b> <br>Effetti sull'ambiente naturale: <b>-</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.578, 42.854 ] } },
{ "type": "Feature", "properties": { "Toponimo": "Balsorano Vecchio (AQ)", "Descrizion": "<br>Latitudine: <b>41.801</b> <br>Longitudine: <b>13.574</b> <br>Intensità segnalata sulla scala Mercalli (MCS): <b>Non classificata</b> <br>Effetti sull'ambiente naturale: <b>Frane, colate di terra e fango (per l'intera sequenza sismica)</b>" }, "geometry": { "type": "Point", "coordinates": [ 13.574, 41.801 ] } }
]
}
